var ExtendedConnector = require('appc.mysql'),
	_ = require('appcelerator').lodash,
	pkginfo = require('pkginfo')(module) && module.exports;

exports.create = function(Arrow, server) {
	return ExtendedConnector.create(Arrow, server).extend({

		/*
		 Configuration.
		 */
		pkginfo: _.pick(pkginfo, 'name', 'version', 'description', 'author', 'license', 'keywords', 'repository'),
		logger: Arrow.createLogger({}, { name: '${ name }', useConsole: true, level: 'debug' })

	});
};
